import { AutoRegisterPush } from "../components/auto-register-push"
import { PushProvider } from "../hooks/use-push"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <PushProvider>
        {children}
        <AutoRegisterPush />
      </PushProvider>
      </body>
    </html>
  )
}
